# Generated by Django 5.1.4 on 2024-12-10 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('unique_id', models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('production_year', models.IntegerField()),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('license_plate', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Car',
            },
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('unique_id', models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Garage',
            },
        ),
        migrations.CreateModel(
            name='CarGarage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_logic.car')),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_logic.garage')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='garages',
            field=models.ManyToManyField(related_name='car_garage', through='backend_logic.CarGarage', to='backend_logic.garage'),
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Repair', 'Repair'), ('Maintenance', 'Maintenance')], max_length=50)),
                ('scheduled_date', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_logic.car')),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_logic.garage')),
            ],
            options={
                'verbose_name': 'Maintenance',
            },
        ),
    ]
